apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 1
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
  - name: ng-3
    instanceType: t2.small
    desiredCapacity: 1 
